replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: 1.1.4
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: sg-app-uat.sg.local
      paths:
        - path: /
          pathType: Prefix
