replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: "dev-01049d2c"

httpRoute:
  hostnames:
    - sg-app-dev.sg.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
