replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: 1.2.0
ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: sg-app-prod.sg.local
      paths:
        - path: /
          pathType: Prefix
