replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: "v1.0.0"
httpRoute:
  hostnames:
    - sg-app-uat.sg.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
