replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: SNAPSHOT-1.1.5
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: sg-app-dev.sg.local
      paths:
        - path: /
          pathType: Prefix
