replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: SNAPSHOT-1.1.3
httpRoute:
  hostnames:
    - sg-app-dev.sg.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
