replicaCount: 1
image:
  repository: tsuweiquan/map-singapore-app
  pullPolicy: IfNotPresent
  tag: SNAPSHOT-1.1.8
ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: sg-app-dev.sg.local
      paths:
        - path: /
          pathType: Prefix
